Repository jupyterlite/xeus, pull requests merged in 2024-02, with the labels that each got.

#59 Fix mount points
  jupyterlite_xeus/add_on.py
  tests/test_xeus.py
Labels: bug

#72 Clean up unused dependencies
  .github/workflows/build.yml
  babel.config.js
  jest.config.js
  package.json
  src/__tests__/jupyterlite_xeus.spec.ts
  tsconfig.test.json
  yarn.lock
Labels: maintenance

#51 Add check for windows absolute path
  jupyterlite_xeus/add_on.py
Labels: enhancement

#71 Support JupyterLite 0.3.0
  .github/workflows/build.yml
  package.json
  pyproject.toml
  ui-tests/tests/jupyterlite_xeus.spec.ts
  ui-tests/tests/jupyterlite_xeus.spec.ts-snapshots/jupyter-xeus-launcher-linux.png
  yarn.lock
Labels: enhancement

#73 JupyterLite-core 0.1.x support
  pyproject.toml
Labels: enhancement

#74 Prevent failing when strict channel priority is set
  jupyterlite_xeus/add_on.py
  tests/environment-1.yml
  tests/environment-2.yml
  tests/test_package/environment-3.yml
Labels: bug

#77 Add `xeus-python` to the example `environment.yml` in the docs
  docs/environment.md
Labels: documentation

#78 Add custom CSS to override the navbar max width
  docs/_static/css/custom.css
  docs/conf.py
Labels: documentation
