Repository jupyterlite/xeus, pull requests merged in 2024-12, with the labels that each got.

#131 Remove unused attributes
  src/worker.ts
Labels: maintenance

#107 Register all kernels in one plugin
  src/index.ts
Labels: enhancement

#132 Split package in two: extension and library
  .gitignore
  lerna.json
  package.json
  packages/xeus-extension/package.json
  packages/xeus-extension/src/index.ts
  packages/xeus-extension/src/tokens.ts
  packages/xeus-extension/tsconfig.json
  packages/xeus/package.json
  packages/xeus/src/coincident.worker.ts
  packages/xeus/src/comlink.worker.ts
  packages/xeus/src/index.ts
  packages/xeus/src/interfaces.ts
  packages/xeus/src/web_worker_kernel.ts
  packages/xeus/src/worker.ts
  packages/xeus/tsconfig.json
  packages/xeus/worker.webpack.config.js
  pyproject.toml
  style/base.css
  style/index.css
  style/index.js
  tsconfig.json
  yarn.lock
Labels: enhancement

#136 Fixing lerna setup
  package.json
  pyproject.toml
  scripts/bump_version.py
Labels: bug

#134 Update JupyterLite packages
  packages/xeus-extension/package.json
  packages/xeus/package.json
  yarn.lock
Labels: enhancement

#130 Bootstrap environments using mambajs, allowing libraries handling for other kernels than xeus-python
  packages/xeus-extension/lab.webpack.config.js
  packages/xeus-extension/package.json
  packages/xeus/package.json
  packages/xeus/src/worker.ts
  yarn.lock
Labels: enhancement

#137 Allow for JupyterLite 0.5.0
  pyproject.toml
Labels: maintenance
