Repository jupyterlite/xeus, pull requests merged in 2024-01, with the labels that each got.

#16 Readme
  README.md
  environment-dev.yaml
  example_envs/env_with_extension.yaml
  example_envs/env_with_many_kernels.yaml
  example_envs/env_with_pip.yaml
Labels: documentation

#18 Fix lint failure on CI
  README.md
Labels: maintenance

#20 Fix ui-tests
  src/index.ts
  ui-tests/tests/jupyterlite_xeus.spec.ts
  ui-tests/yarn.lock
Labels: maintenance

#19 Update to a comma-separated list of mount points
  jupyterlite_xeus/add_on.py
Labels: enhancement

#22 fixed minor typos in README.md
  README.md
Labels: documentation

#25 update README.md with JupyterLite site instructions
  README.md
Labels: documentation

#26 Add a simple UI-test
  .github/workflows/build.yml
  .github/workflows/update-integration-tests.yml
  .gitignore
  environment-dev.yaml
  ui-tests/build.py
  ui-tests/environment.yml
  ui-tests/jupyter-lite.json
  ui-tests/jupyter_lite_config.json
  ui-tests/jupyter_server_test_config.py
  ui-tests/package.json
  ui-tests/playwright.config.js
  ui-tests/tests/jupyterlite_xeus.spec.ts
  ui-tests/tests/jupyterlite_xeus.spec.ts-snapshots/jupyter-xeus-execute-linux.png
  ui-tests/tests/jupyterlite_xeus.spec.ts-snapshots/jupyter-xeus-launcher-linux.png
  ui-tests/yarn.lock
Labels: maintenance

#28 Remove broken link
  ui-tests/README.md
Labels: documentation

#23 Rework xeus output paths and URLs
  jupyterlite_xeus/add_on.py
  src/index.ts
  src/web_worker_kernel.ts
  src/worker.ts
Labels: enhancement

#31 Missing jupyterlite in galata bot
  .github/workflows/update-integration-tests.yml
Labels: maintenance

#30 Update test to match the new xeus-python
  ui-tests/environment.yml
  ui-tests/tests/jupyterlite_xeus.spec.ts
  ui-tests/tests/jupyterlite_xeus.spec.ts-snapshots/jupyter-xeus-launcher-linux.png
  yarn.lock
Labels: maintenance

#29 Ruff linting
  .github/workflows/build.yml
  jupyterlite_xeus/__init__.py
  jupyterlite_xeus/_pip.py
  jupyterlite_xeus/add_on.py
  jupyterlite_xeus/create_conda_env.py
  pyproject.toml
Labels: maintenance

#34 Attempt to fix the base_url from the worker
  src/web_worker_kernel.ts
  src/worker.ts
Labels: bug

#35 Fix missing dependencies
  pyproject.toml
Labels: bug

#36 SVG Icon
  src/index.ts
Labels: enhancement

#37 Show warning if there is no kernel in the prefix
  jupyterlite_xeus/add_on.py
Labels: enhancement

#38 Bring back empack filtering
  jupyterlite_xeus/add_on.py
  pyproject.toml
Labels: enhancement

#39 Bring back jupyterlite-xeus-python unit tests
  .github/workflows/build.yml
  README.md
  environment-dev.yaml
  jupyterlite_xeus/add_on.py
  jupyterlite_xeus/create_conda_env.py
  tests/environment-1.yml
  tests/environment-2.yml
  tests/test_package/environment-3.yml
  tests/test_package/pyproject.toml
  tests/test_package/test_package/__init__.py
  tests/test_package/test_package/hey.py
  tests/test_xeus.py
Labels: maintenance

#40 Improve image loading logic
  jupyterlite_xeus/add_on.py
  jupyterlite_xeus/create_conda_env.py
  src/index.ts
Labels: bug

#42 Fix path to logo assets
  jupyterlite_xeus/add_on.py
  ui-tests/playwright.config.js
  ui-tests/tests/jupyterlite_xeus.spec.ts-snapshots/jupyter-xeus-launcher-linux.png
Labels: bug

#46 Update README
  README.md
Labels: documentation

#47 Fix: Path to environment file should be relative to the lite dir
  jupyterlite_xeus/add_on.py
Labels: bug

#48 Prevent from failing if there is no environment file
  jupyterlite_xeus/add_on.py
Labels: bug

#49 Allow mounting jupyterlite content
  jupyterlite_xeus/add_on.py
  src/web_worker_kernel.ts
  src/worker.ts
Labels: enhancement

#50 Add documentation
  .readthedocs.yaml
  docs/advanced.md
  docs/build-environment.yml
  docs/changelog.md
  docs/conf.py
  docs/deploy.md
  docs/environment.md
  docs/environment.yml
  docs/files.md
  docs/index.md
  docs/jupyterlite.svg
  docs/xeus.svg
Labels: documentation

#54 Docs: add note about behavior in Voici
  docs/files.md
Labels: documentation

#55 Fix voici check
  jupyterlite_xeus/add_on.py
Labels: bug

#57 Prevent using package caching
  jupyterlite_xeus/add_on.py
Labels: bug
