Repository jupyterlite/xeus, pull requests merged in 2024-05, with the labels that each got.

#88 give micromamba priority
  jupyterlite_xeus/create_conda_env.py
Labels: bug, HOTFIX

#89 Fix ReadTheDocs build
  docs/build-environment.yml
Labels: documentation

#91 Update ipywidgets in docs
  docs/environment.yml
  docs/index.md
Labels: documentation

#90 Allow for JupyterLite 0.4.0
  package.json
  pyproject.toml
  yarn.lock
Labels: maintenance
