Repository jupyterlite/xeus, pull requests merged in 2025-03, with the labels that each got.

#192 Snapshot the notebook section of the launcher only
  ui-tests/tests/jupyterlite_xeus.spec.ts
  ui-tests/tests/jupyterlite_xeus.spec.ts-snapshots/jupyter-xeus-launcher-crossoriginisolated-linux.png
  ui-tests/tests/jupyterlite_xeus.spec.ts-snapshots/jupyter-xeus-launcher-default-linux.png
Labels: maintenance

#198 Debug docs
  docs/build-environment.yml
Labels: documentation

#203 Bring back mount points as list
  docs/files.md
  jupyterlite_xeus/add_on.py
Labels: enhancement

#191 Installing xeus-cpp from prefix-dev
  docs/environment-cpp.yml
Labels: enhancement

#204 Update jupyterlite 0.6.0-alpha.3: remove split liteextension/labextension
  .github/workflows/build.yml
  .github/workflows/update-integration-tests.yml
  .gitignore
  docs/build-environment.yml
  jupyterlite_xeus/__init__.py
  packages/xeus-extension/lab.webpack.config.js
  packages/xeus-extension/package.json
  packages/xeus-extension/src/index.ts
  packages/xeus-extension/src/tokens.ts
  packages/xeus-kernels-extension/package.json
  packages/xeus-kernels-extension/src/index.ts
  packages/xeus-kernels-extension/tsconfig.json
  packages/xeus/package.json
  pyproject.toml
  yarn.lock
Labels: maintenance

#205 Update mambajs
  packages/xeus-extension/src/index.ts
  packages/xeus/package.json
  yarn.lock
Labels: maintenance

#207 3.x: Update mambajs
  docs/build-environment.yml
  packages/xeus/package.json
  packages/xeus/src/worker.ts
  ui-tests/tests/jupyterlite_xeus.spec.ts-snapshots/jupyter-xeus-launcher-crossoriginisolated-linux.png
  ui-tests/tests/jupyterlite_xeus.spec.ts-snapshots/jupyter-xeus-launcher-default-linux.png
  yarn.lock
Labels: enhancement
