Repository jupyterlite/xeus, pull requests merged in 2025-01, with the labels that each got.

#140 Update bot triggering logic
  .github/workflows/update-integration-tests.yml
Labels: maintenance

#139 Fix empack custom config support
  jupyterlite_xeus/add_on.py
  pyproject.toml
  ui-tests/tests/jupyterlite_xeus.spec.ts-snapshots/jupyter-xeus-execute-crossoriginisolated-linux.png
  ui-tests/tests/jupyterlite_xeus.spec.ts-snapshots/jupyter-xeus-execute-default-linux.png
  ui-tests/tests/jupyterlite_xeus.spec.ts-snapshots/jupyter-xeus-launcher-crossoriginisolated-linux.png
  ui-tests/tests/jupyterlite_xeus.spec.ts-snapshots/jupyter-xeus-launcher-default-linux.png
Labels: bug

#144 Update mambajs
  .readthedocs.yaml
  environment-dev.yaml
  packages/xeus/package.json
  packages/xeus/src/worker.ts
  yarn.lock
Labels: maintenance

#146 Kernel shared libs handling
  jupyterlite_xeus/add_on.py
  packages/xeus/src/worker.ts
Labels: enhancement

#149 Update mambajs 0.2.1
  packages/xeus/package.json
  yarn.lock
Labels: enhancement

#151 Add 0.5.0 version specifier
  packages/xeus-extension/package.json
  packages/xeus/package.json
  yarn.lock
Labels: maintenance

#153 Update actions
  .github/workflows/build.yml
  .github/workflows/check-release.yml
Labels: maintenance

#152 Add xeus-r
  docs/environment.yml
Labels: documentation

#156 Remove xeus-r from docs for now
  docs/environment.yml
Labels: documentation

#154 Use new mambajs splitted API
  packages/xeus/package.json
  packages/xeus/src/worker.ts
  yarn.lock
Labels: maintenance

#155 Adding back xeus-r in docs
  docs/environment.yml
  docs/index.md
  packages/xeus/src/worker.ts
  ui-tests/environment.yml
Labels: documentation

#157 Update ui-tests screenshots
  ui-tests/tests/jupyterlite_xeus.spec.ts-snapshots/jupyter-xeus-launcher-crossoriginisolated-linux.png
  ui-tests/tests/jupyterlite_xeus.spec.ts-snapshots/jupyter-xeus-launcher-default-linux.png
Labels: maintenance

#159 Update mambajs and untarjs
  packages/xeus/package.json
  packages/xeus/src/worker.ts
  yarn.lock
Labels: enhancement

#161 Add support for using Python 3.13
  docs/environment.md
  jupyterlite_xeus/create_conda_env.py
  ui-tests/tests/jupyterlite_xeus.spec.ts-snapshots/jupyter-xeus-launcher-crossoriginisolated-linux.png
  ui-tests/tests/jupyterlite_xeus.spec.ts-snapshots/jupyter-xeus-launcher-default-linux.png
Labels: enhancement

#163 Improve docs landing page
  docs/build-environment.yml
  docs/conf.py
  docs/index.md
Labels: documentation

#165 Non verbose env bootstrap in production
  packages/xeus/src/worker.ts
Labels: enhancement

#166 Rebuild with untarjs 5.2.1
  yarn.lock
Labels: enhancement

#164 Multi envs support
  docs/environment-other.yml
  docs/environment-python.yml
  docs/environment-r.yml
  docs/jupyter_lite_config.json
  jupyterlite_xeus/add_on.py
  jupyterlite_xeus/create_conda_env.py
  packages/xeus/src/worker.ts
  tests/test_xeus.py
Labels: enhancement

#169 Fix cwd when building the environment
  jupyterlite_xeus/add_on.py
Labels: bug

#171 Rebuild with latest jupyterlite
  packages/xeus-extension/package.json
  packages/xeus/package.json
  yarn.lock
Labels: maintenance

#173 Backport https://github.com/jupyterlite/xeus/pull/171: rebuild with latest jupyterlite
  packages/xeus-extension/package.json
  packages/xeus/package.json
  yarn.lock
Labels: maintenance

#178 Backport: Non-hardcoded python version (#177)
  jupyterlite_xeus/_pip.py
  jupyterlite_xeus/constants.py
Labels: bug

#179 Python 3.13 on docs
  docs/environment-python.yml
  ui-tests/tests/jupyterlite_xeus.spec.ts-snapshots/jupyter-xeus-launcher-crossoriginisolated-linux.png
  ui-tests/tests/jupyterlite_xeus.spec.ts-snapshots/jupyter-xeus-launcher-default-linux.png
Labels: documentation
