Repository jupyterlite/xeus, pull requests merged in 2025-07, with the labels that each got.

#254 Add package removing logic
  jupyterlite_xeus/add_on.py
  packages/xeus-core/package.json
  packages/xeus-core/src/worker.base.ts
  packages/xeus/package.json
  packages/xeus/src/worker.ts
  tests/test_xeus.py
  yarn.lock
Labels: enhancement

#258 Fix support for kernels from the old beta.mamba.pm channel
  packages/xeus/src/worker.ts
  ui-tests/env3.yml
Labels: bug

#261 Match real pip's error message for uninstalling non-installed pkg
  packages/xeus/src/worker.ts
Labels: enhancement

#269 Quickstart docs
  README.md
  docs/index.md
Labels: documentation

#270 Handle case where there is no kernel in the environment
  jupyterlite_xeus/add_on.py
  tests/environment-4.yml
  tests/test_xeus.py
Labels: bug
