Repository jupyterlite/xeus, pull requests merged in 2025-05, with the labels that each got.

#220 Use `/api/stdin/kernel` for stdin requests via service worker
  packages/xeus/src/comlink.worker.ts
Labels: enhancement

#221 Update JupyterLite and JupyterLab - stdin support + use kernel logs UI
  docs/build-environment.yml
  environment-dev.yaml
  packages/xeus-extension/package.json
  packages/xeus-extension/src/index.ts
  packages/xeus-extension/style/base.css
  packages/xeus-extension/style/index.css
  packages/xeus-extension/style/index.js
  packages/xeus/package.json
  packages/xeus/src/web_worker_kernel.ts
  packages/xeus/src/worker.ts
  pyproject.toml
  yarn.lock
Labels: maintenance

#208 Install packages dynamically
  jupyterlite_xeus/create_conda_env.py
  packages/xeus/package.json
  packages/xeus/src/web_worker_kernel.ts
  packages/xeus/src/worker.ts
  tests/test_xeus.py
  yarn.lock
Labels: enhancement

#223 Separate deployment directory for each xeus environment
  jupyterlite_xeus/add_on.py
  packages/xeus-extension/src/index.ts
  packages/xeus/src/worker.ts
  tests/environment-3.yml
  tests/test_xeus.py
Labels: enhancement

#225 Support the same kernel in multiple environments
  packages/xeus-extension/src/index.ts
Labels: enhancement

#222 Making the kernel worker more extensible
  packages/xeus-extension/package.json
  packages/xeus/package.json
  packages/xeus/src/coincident.worker.ts
  packages/xeus/src/comlink.worker.ts
  packages/xeus/src/index.ts
  packages/xeus/src/worker.base.ts
  packages/xeus/src/worker.ts
  yarn.lock
Labels: enhancement

#230 Update mambajs: fix %pip install command
  packages/xeus-core/package.json
  packages/xeus/package.json
  yarn.lock
Labels: enhancement

#231 Install micromamba 2.0.5 in update-snapshots gha
  .github/workflows/update-integration-tests.yml
Labels: maintenance

#232 Update docs for coming 4.0.0 release
  README.md
  docs/advanced.md
  docs/environment.md
  docs/index.md
Labels: documentation

#229 Add UI test for multiple python kernels in different environments
  ui-tests/env1.yml
  ui-tests/env2.yml
  ui-tests/jupyter_lite_config.json
  ui-tests/tests/jupyterlite_xeus.spec.ts
  ui-tests/tests/jupyterlite_xeus.spec.ts-snapshots/jupyter-xeus-execute-env2-crossoriginisolated-linux.png
  ui-tests/tests/jupyterlite_xeus.spec.ts-snapshots/jupyter-xeus-execute-env2-default-linux.png
  ui-tests/tests/jupyterlite_xeus.spec.ts-snapshots/jupyter-xeus-launcher-crossoriginisolated-linux.png
  ui-tests/tests/jupyterlite_xeus.spec.ts-snapshots/jupyter-xeus-launcher-default-linux.png
Labels: maintenance

#234 Fix missing labextensions settings
  jupyterlite_xeus/add_on.py
Labels: bug

#236 Do not use refreshSpecs
  packages/xeus-extension/src/index.ts
Labels: bug
